= Cheatsheets

[[RabbitMQOptions]]
== RabbitMQOptions

++++
RabbitMQ client options, most
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[automaticRecoveryEnabled]]`automaticRecoveryEnabled`|`Boolean`|
+++
Enables or disables automatic connection recovery.
+++
|[[connectionRetries]]`connectionRetries`|`Number (Integer)`|
+++
Set the number of connection retries to attempt when connecting, the <code>null</code> value disables it.
+++
|[[connectionRetryDelay]]`connectionRetryDelay`|`Number (long)`|
+++
Set the delay in milliseconds between connection retries.
+++
|[[connectionTimeout]]`connectionTimeout`|`Number (int)`|
+++
Set the TCP connection timeout, in milliseconds, <code>zero</code> for infinite).
+++
|[[handshakeTimeout]]`handshakeTimeout`|`Number (int)`|
+++
Set the AMQP 0-9-1 protocol handshake timeout, in milliseconds
+++
|[[host]]`host`|`String`|
+++
Set the default host to use for connections.
+++
|[[includeProperties]]`includeProperties`|`Boolean`|
+++
Set wether to include properties when a broker message is passed on the event bus
+++
|[[networkRecoveryInterval]]`networkRecoveryInterval`|`Number (long)`|
+++
Set how long in milliseconds will automatic recovery wait before attempting to reconnect, default is <code>5000</code>
+++
|[[password]]`password`|`String`|
+++
Set the password to use when connecting to the broker.
+++
|[[port]]`port`|`Number (int)`|
+++
Set the default port to use for connections.
+++
|[[requestedChannelMax]]`requestedChannelMax`|`Number (int)`|
+++
Set the initially requested maximum channel number, <code>zero</code> for unlimited.
+++
|[[requestedHeartbeat]]`requestedHeartbeat`|`Number (int)`|
+++
Set the initially requested heartbeat interval, in seconds, <code>zero</code> for none.
+++
|[[uri]]`uri`|`String`|-
|[[user]]`user`|`String`|
+++
Set the AMQP user name to use when connecting to the broker.
+++
|[[virtualHost]]`virtualHost`|`String`|
+++
Set the virtual host to use when connecting to the broker.
+++
|===