=== Docker Links bridge

This discovery bridge imports services from Docker Links into the Vert.x service discovery. When you link a Docker
container to another Docker container, Docker injects a set of environment variables. This bridge analyzes these
environment variables and imports service record for each link. The service type is deduced from the `service.type`
label. If not set, the service is imported as `unknown`. Only `http-endpoint` are supported for now.

As the links are created when the container starts, the imported records are created when the bridge starts and
do not change afterwards.

==== Using the bridge

To use this Vert.x discovery bridge, add the following dependency to the _dependencies_ section of your build
descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
 <groupId>${maven.groupId}</groupId>
 <artifactId>${maven.artifactId}</artifactId>
 <version>${maven.version}</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile '${maven.groupId}:${maven.artifactId}:${maven.version}'
----

Then, when creating the service discovery, registers this bridge as follows:

[source, scala]
----
ServiceDiscovery.create(vertx).registerServiceImporter(new io.vertx.servicediscovery.docker.DockerLinksServiceImporter(), new io.vertx.core.json.JsonObject())

----

The bridge does not need any further configuration.