= Vert.x Scala

image:https://github.com/vert-x3/vertx-lang-scala/actions/workflows/ci.yml/badge.svg["Build Status",link="https://github.com/vert-x3/vertx-lang-scala/actions/workflows/ci.yml"]
image:https://img.shields.io/maven-central/v/io.vertx/vertx-lang-scala_3.svg["Maven Central"]

Vert.x-Scala provides language bindings and helpers for a more idiomatic use of Vert.x with Scala.

Please see the main documentation on the web-site for a full description:

* http://vert-x3.github.io/vertx-lang-scala/[Web-site documentation]

=== For Developers
The following sections explain how to **use** Vert.x-Scala.

=== Getting started with sbt
There is a Giter8 template to get you started real quickly with sbt:

```shell
sbt new https://github.com/vert-x3/vertx-scala.g8
```

=== Getting started with Maven/Gradle
We are working on a starter configuration for https://start.vertx.io[start.vertx.io]. You should be able to generate a starter project soon from there.

== For Maintainers
The following sections are for maintainers of this software.

=== Releasing
In order to perform a release of this software,

  1. Set the release version in the aggregator `pom.xml` and all modules' `pom.xml` files
  2. Commit, build and push to Maven Central
  3. Set the next SNAPSHOT version in the aggregator `pom.xml` and all modules' `pom.xml` files
