= Vert.x for Scala

If you are using Maven or Gradle, add the following dependency to the _dependencies_ section of your
project descriptor to access the Vert.x Core API and enable the Kotlin support:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
 <groupId>io.vertx</groupId>
 <artifactId>vertx-core</artifactId>
 <version>${maven.version}</version>
</dependency>
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-lang-scala</artifactId>
  <version>${maven.version}</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile "io.vertx:vertx-core:${maven.version}"
compile "io.vertx:vertx-lang-scala:${maven.version}"
----

* SBT (in your `build.sbt` file):

[source,scala,subs="+attributes"]
----
libraryDependencies += "io.vertx" % "vertx-core" % "${maven.version}"
libraryDependencies += "io.vertx" %% "vertx-lang-scala" % "${maven.version}"
----
== Vert.x and Scala
For Vert.x 4 we completely reworked Scala-integration works. In the past we had a heavy wrapping layer around every single part of the Vert.x-API which added a lot of indirections and increased the allocastion rate quite a bit.
Since then a lot of things have changed. Vert.x and Scala moved quite a bit closer. The usage of fluent APIs, Futures and the likes finally made it into the core. Many idioms from the Scala world were finally available and made it way easier to integrate the both.
The current approach relies on a few conversions and a small set of helper classes to bridge the gap.

== Quickstart

== Helpers

Whether you are using Verticles or plain Vert.x, when using Scala you should always have *io.vertx.lang.scala._* imported.

[source, scala]
----
import io.vertx.lang.scala._
----

That package provides conversions between VertxFutures and their Scala counterparts.

== Using Verticles

For Scala-based verticles we provide {@link io.vertx.lang.scala.ScalaVerticle}. Extending this class
gives you everything needed.

[source, scala]
----
import scala.concurrent.Future

import io.vertx.lang.scala.ScalaVerticle
import io.vertx.lang.scala._

class StartFutureVerticle extends ScalaVerticle{
  override def startFuture(): Future[Unit] = {
    Future.successful()
  }

  override def stopFuture(): Future[Unit] = {
    Future.successful()
  }

  def start(): Unit = {
  }

  def stop(): Unit = {
  }
}
----

The biggest differences between this and {@link io.vertx.core.AbstractVerticle} are the addition of startFuture/stopFuture and the existence of an implicit {@link io.vertx.lang.scala.VertxExecutionContext}.

== Using Vert.x without Verticles


== JSON

====

====

