= Cheatsheets

[[DropwizardMetricsOptions]]
== DropwizardMetricsOptions

++++
Vert.x Dropwizard metrics configuration.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[baseName]]`@baseName`|`String`|+++
Set a custom baseName for metrics.
+++
|[[configPath]]`@configPath`|`String`|+++
Set the path for a config file that contains options in JSON format, to be used to create a new options object.
The file will be looked for on the file system first and then on the classpath if it's not found.
+++
|[[enabled]]`@enabled`|`Boolean`|-
|[[jmxDomain]]`@jmxDomain`|`String`|+++
Set the JMX domain to use when JMX metrics are enabled.
+++
|[[jmxEnabled]]`@jmxEnabled`|`Boolean`|+++
Set whether JMX will be enabled on the Vert.x instance.
+++
|[[registryName]]`@registryName`|`String`|+++
Set the name used for registering the metrics in the Dropwizard shared registry.
+++
|===

[[Match]]
== Match

++++
A match for a value.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[alias]]`@alias`|`String`|+++
Set the alias the human readable name that will be used as a part of
registry entry name when the value matches.
+++
|[[type]]`@type`|`link:enums.html#MatchType[MatchType]`|+++
Set the type of matching to apply.
+++
|[[value]]`@value`|`String`|+++
Set the matched value.
+++
|===