= Reactive MySQL Client
:PREPARED_PARAMS: `?`

The Reactive MySQL Client is a client for MySQL with a straightforward API focusing on
scalability and low overhead.

*Features*

* Event driven
* Lightweight
* Built-in connection pooling
* Prepared queries caching
* Cursor support
* Row streaming
* RxJava 1 and RxJava 2
* Direct memory to object without unnecessary copies
* Java 8 Date and Time
* Stored Procedures support
* TLS/SSL support
* MySQL utilities commands support
* Working with MySQL and MariaDB
* Rich collation and charset support

== Usage

To use the Reactive MySQL Client add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml]
----
<dependency>
 <groupId>${maven.groupId}</groupId>
 <artifactId>${maven.artifactId}</artifactId>
 <version>${maven.version}</version>
</dependency>
----
* Gradle (in your `build.gradle` file):

[source,groovy]
----
dependencies {
 compile '${maven.groupId}:${maven.artifactId}:${maven.version}'
}
----

== Getting started

Here is the simplest way to connect, query and disconnect

[source,scala]
----

// Connect options
var connectOptions = MySQLConnectOptions()
  .setPort(3306)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret")


// Pool options
var poolOptions = PoolOptions()
  .setMaxSize(5)


// Create the client pool
var client = MySQLPool.pool(connectOptions, poolOptions)

// A simple query
client.queryFuture("SELECT * FROM users WHERE id='julien'").onComplete{
  case Success(result) => println("Success")
  case Failure(cause) => println("Failure")
}

----

== Connecting to MySQL

Most of the time you will use a pool to connect to MySQL:

[source,scala]
----

// Connect options
var connectOptions = MySQLConnectOptions()
  .setPort(3306)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret")


// Pool options
var poolOptions = PoolOptions()
  .setMaxSize(5)


// Create the pooled client
var client = MySQLPool.pool(connectOptions, poolOptions)

----

The pooled client uses a connection pool and any operation will borrow a connection from the pool
to execute the operation and release it to the pool.

If you are running with Vert.x you can pass it your Vertx instance:

[source,scala]
----

// Connect options
var connectOptions = MySQLConnectOptions()
  .setPort(3306)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret")


// Pool options
var poolOptions = PoolOptions()
  .setMaxSize(5)

// Create the pooled client
var client = MySQLPool.pool(vertx, connectOptions, poolOptions)

----

You need to release the pool when you don't need it anymore:

[source,scala]
----

// Close the pool and all the associated resources
pool.close()

----

When you need to execute several operations on the same connection, you need to use a client
`link:../../scaladocs/io/vertx/scala/mysqlclient/MySQLConnection.html[connection]`.

You can easily get one from the pool:

[source,scala]
----

// Connect options
var connectOptions = MySQLConnectOptions()
  .setPort(3306)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret")


// Pool options
var poolOptions = PoolOptions()
  .setMaxSize(5)


// Create the pooled client
var client = MySQLPool.pool(vertx, connectOptions, poolOptions)

// Get a connection from the pool
client.getConnectionFuture().onComplete{
  case Success(result) => {

    println("Connected")

    // Obtain our connection
    var conn = result

    // All operations execute on the same connection
    conn.queryFuture("SELECT * FROM users WHERE id='julien'").onComplete{
      case Success(result) => {
        conn.queryFuture("SELECT * FROM users WHERE id='emad'").onComplete{
          case Success(result) => println("Success")
          case Failure(cause) => println("Failure")
        }
      }
      case Failure(cause) => {
        println(s"$cause")
      }
    }
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

Once you are done with the connection you must close it to release it to the pool, so it can be reused.

== Configuration

There are several alternatives for you to configure the client.

=== Data Object

A simple way to configure the client is to specify a `MySQLConnectOptions` data object.

[source,scala]
----

// Data object
var connectOptions = MySQLConnectOptions()
  .setPort(3306)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret")


// Pool Options
var poolOptions = PoolOptions()
  .setMaxSize(5)


// Create the pool from the data object
var pool = MySQLPool.pool(vertx, connectOptions, poolOptions)

pool.getConnectionFuture().onComplete{
  case Success(result) => println("Success")
  case Failure(cause) => println("Failure")
}

----

==== collations and character sets

The Reactive MySQL client supports configuring collations or character sets and map them to a correlative `java.nio.charset.Charset`.
For example, you can specify charset for a connection like

[source,scala]
----
var connectOptions = MySQLConnectOptions()

// set connection character set to utf8 instead of the default charset utf8mb4
connectOptions.setCharset("utf8")

----

The Reactive MySQL Client will take `utf8mb4` as the default charset. String values like password and error messages are always decoded in `UTF-8` charset.

`characterEncoding` option is used to determine which Java charset will be used to encode String values such as query string and parameter values, the charset is `UTF-8` by default and if it's set to `null` then the client will use the default Java charset instead.

You can also specify collation for a connection like

[source,scala]
----
var connectOptions = MySQLConnectOptions()

// set connection collation to utf8_general_ci instead of the default collation utf8mb4_general_ci
// setting a collation will override the charset option
connectOptions.setCharset("gbk")
connectOptions.setCollation("utf8_general_ci")

----

Note setting a collation on the data object will override the *charset* and *characterEncoding* option.

You can execute SQL `SHOW COLLATION;` or `SHOW CHARACTER SET;` to get the supported collations and charsets by the server.

More information about MySQL charsets and collations can be found in the https://dev.mysql.com/doc/refman/8.0/en/charset.html[MySQL Reference Manual].

==== connection attributes

You can also configure the connection attributes with the `setProperties` or `addProperty` methods. Note `setProperties` will override the default client properties.

[source,scala]
----
Code not translatable
----

More information about client connection attributes can be found in the https://dev.mysql.com/doc/refman/8.0/en/performance-schema-connection-attribute-tables.html[MySQL Reference Manual].

==== useAffectedRows

You can configure the `useAffectedRows` option to decide whether to set `CLIENT_FOUND_ROWS` flag when connecting to the server. If the `CLIENT_FOUND_ROWS` flag is specified then the affected rows count is the numeric value of rows found rather than affected.

More information about this can be found in the https://dev.mysql.com/doc/refman/8.0/en/mysql-affected-rows.html[MySQL Reference Manual]

=== connection URI

Apart from configuring with a `MySQLConnectOptions` data object, We also provide you an alternative way to connect when you want to configure with a connection URI:

[source,scala]
----

// Connection URI
var connectionUri = "mysql://dbuser:secretpassword@database.server.com:3211/mydb"

// Create the pool from the connection URI
var pool = MySQLPool.pool(connectionUri)

// Create the connection from the connection URI
MySQLConnection.connect(vertx, connectionUri, {
  case Success(result) => println("Success")
  case Failure(cause) => println("Failure")
})

----

More information about connection string formats can be found in the https://dev.mysql.com/doc/refman/8.0/en/connecting-using-uri-or-key-value-pairs.html#connecting-using-uri[MySQL Reference Manual].

Currently the client supports the following parameter key words in connection uri(keys are case-insensitive)

* host
* port
* user
* password
* schema
* socket
* useAffectedRows

include::queries.adoc[]

== MySQL LAST_INSERT_ID

You can get the auto incremented value if you insert a record into the table.

[source,scala]
----
client.queryFuture("INSERT INTO test(val) VALUES ('v1')").onComplete{
  case Success(result) => {
    var rows = result
    var lastInsertId = rows.property(MySQLClient.LAST_INSERTED_ID)
    println(s"Last inserted id is: ${lastInsertId}")
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

More information can be found in https://dev.mysql.com/doc/refman/8.0/en/getting-unique-id.html[How to Get the Unique ID for the Last Inserted Row].

include::connections.adoc[]

include::transactions.adoc[]

include::cursor.adoc[]

== MySQL type mapping

Currently the client supports the following MySQL types

* BOOL,BOOLEAN (`java.lang.Byte`)
* TINYINT (`java.lang.Byte`)
* TINYINT UNSIGNED(`java.lang.Short`)
* SMALLINT (`java.lang.Short`)
* SMALLINT UNSIGNED(`java.lang.Integer`)
* MEDIUMINT (`java.lang.Integer`)
* MEDIUMINT UNSIGNED(`java.lang.Integer`)
* INT,INTEGER (`java.lang.Integer`)
* INTEGER UNSIGNED(`java.lang.Long`)
* BIGINT (`java.lang.Long`)
* BIGINT UNSIGNED(`io.vertx.sqlclient.data.Numeric`)
* FLOAT (`java.lang.Float`)
* FLOAT UNSIGNED(`java.lang.Float`)
* DOUBLE (`java.lang.Double`)
* DOUBLE UNSIGNED(`java.lang.Double`)
* BIT (`java.lang.Long`)
* NUMERIC (`io.vertx.sqlclient.data.Numeric`)
* NUMERIC UNSIGNED(`io.vertx.sqlclient.data.Numeric`)
* DATE (`java.time.LocalDate`)
* DATETIME (`java.time.LocalDateTime`)
* TIME (`java.time.Duration`)
* TIMESTAMP (`java.time.LocalDateTime`)
* YEAR (`java.lang.Short`)
* CHAR (`java.lang.String`)
* VARCHAR (`java.lang.String`)
* BINARY (`io.vertx.core.buffer.Buffer`)
* VARBINARY (`io.vertx.core.buffer.Buffer`)
* TINYBLOB (`io.vertx.core.buffer.Buffer`)
* TINYTEXT (`java.lang.String`)
* BLOB (`io.vertx.core.buffer.Buffer`)
* TEXT (`java.lang.String`)
* MEDIUMBLOB (`io.vertx.core.buffer.Buffer`)
* MEDIUMTEXT (`java.lang.String`)
* LONGBLOB (`io.vertx.core.buffer.Buffer`)
* LONGTEXT (`java.lang.String`)
* ENUM (`java.lang.String`)
* SET (`java.lang.String`)
* JSON (`io.vertx.core.json.JsonObject`, `io.vertx.core.json.JsonArray`, `Number`, `Boolean`, `String`, `io.vertx.sqlclient.Tuple#JSON_NULL`)

Tuple decoding uses the above types when storing values

Note: In Java there is no specific representations for unsigned numeric values, so this client will convert an unsigned value to the correlated Java type.

=== Implicit type conversion

The Reactive MySQL Client supports implicit type conversions when executing a prepared statement.
Suppose you have a `TIME` column in your table, the two examples below will both work here.

[source,scala]
----
client.preparedQueryFuture("SELECT * FROM students WHERE updated_time = ?", Tuple.of(java.time.LocalTime.of(19, 10, 25))).onComplete{
  case Success(result) => println("Success")
  case Failure(cause) => println("Failure")
}
// this will also work with implicit type conversion
client.preparedQueryFuture("SELECT * FROM students WHERE updated_time = ?", Tuple.of("19:10:25")).onComplete{
  case Success(result) => println("Success")
  case Failure(cause) => println("Failure")
}

----

The MySQL data type for encoding will be inferred from the parameter values and here is the type mapping

|===
|Parameter value type |encoding MySQL type

|null
|MYSQL_TYPE_NULL

|java.lang.Byte
|MYSQL_TYPE_TINY

|java.lang.Boolean
|MYSQL_TYPE_TINY

|java.lang.Short
|MYSQL_TYPE_SHORT

|java.lang.Integer
|MYSQL_TYPE_LONG

|java.lang.Long
|MYSQL_TYPE_LONGLONG

|java.lang.Double
|MYSQL_TYPE_DOUBLE

|java.lang.Float
|MYSQL_TYPE_FLOAT

|java.time.LocalDate
|MYSQL_TYPE_DATE

|java.time.Duration
|MYSQL_TYPE_TIME

|io.vertx.core.buffer.Buffer
|MYSQL_TYPE_BLOB

|java.time.LocalDateTime
|MYSQL_TYPE_DATETIME

|default
|MYSQL_TYPE_STRING
|===

=== Handling BOOLEAN

In MySQL `BOOLEAN` and `BOOL` data types are synonyms for `TINYINT(1)`. A value of zero is considered false, non-zero values are considered true.
A `BOOLEAN` data type value is stored in `Row` or `Tuple` as `java.lang.Byte` type, you can call `Row#getValue` to retrieve it as a `java.lang.Byte` value,
or you can call `Row#getBoolean` to retrieve it as `java.lang.Boolean` value.

[source,scala]
----
client.queryFuture("SELECT graduated FROM students WHERE id = 0").onComplete{
  case Success(result) => {
    var rowSet = result
    rowSet.foreach(row => {
      var pos = row.getColumnIndex("graduated")
      var value = row.get(java.lang.Byte.class, pos)
      var graduated = row.getBoolean("graduated")
    })

  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

When you want to execute a prepared statement with a param of a `BOOLEAN` value, you can simply add the `java.lang.Boolean` value to the params list.

[source,scala]
----
client.preparedQueryFuture("UPDATE students SET graduated = ? WHERE id = 0", Tuple.of(true)).onComplete{
  case Success(result) => {
    println("Updated with the boolean value")
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

=== Handling JSON

MySQL `JSON` data type is represented by the following Java types:

- `String`
- `Number`
- `Boolean`
- `io.vertx.core.json.JsonObject`
- `io.vertx.core.json.JsonArray`
- `io.vertx.sqlclient.Tuple#JSON_NULL` for representing the JSON null literal

[source,scala]
----
Code not translatable
----

=== Handling BIT
The `BIT` data type is mapped to `java.lang.Long` type, but Java has no notion of unsigned numeric values, so if you want to insert or update a record with the max value of `BIT(64)`, you can do some tricks setting the parameter to `-1L`.

=== Handling NUMERIC

The `Numeric` Java type is used to represent the MySQL `NUMERIC` type.

[source,scala]
----
var numeric = row.get(io.vertx.sqlclient.data.Numeric.class, 0)
if (numeric.isNaN()) {
  // Handle NaN
} else {
  var value = numeric.bigDecimalValue()
}

----

== Collector queries

You can use Java collectors with the query API:

[source,scala]
----
Code not translatable
----

The collector processing must not keep a reference on the `link:../../scaladocs/io/vertx/scala/sqlclient/Row.html[Row]` as
there is a single row used for processing the entire set.

The Java `Collectors` provides many interesting predefined collectors, for example you can
create easily create a string directly from the row set:

[source,scala]
----
Code not translatable
----

== MySQL Stored Procedure

You can run stored procedures in queries. The result will be retrieved from the server following the https://dev.mysql.com/doc/dev/mysql-server/8.0.12/page_protocol_command_phase_sp.html[MySQL protocol] without any magic here.

[source,scala]
----
client.queryFuture("CREATE PROCEDURE multi() BEGIN\n  SELECT 1;\n  SELECT 1;\n  INSERT INTO ins VALUES (1);\n  INSERT INTO ins VALUES (2);\nEND;").onComplete{
  case Success(result) => {
    // create stored procedure success
    client.queryFuture("CALL multi();").onComplete{
      case Success(result) => {
        // handle the result
        var result1 = result
        var row1 = result1.iterator().next()
        println(s"First result: ${row1.getInteger(0)}")

        var result2 = result1.next()
        var row2 = result2.iterator().next()
        println(s"Second result: ${row2.getInteger(0)}")

        var result3 = result2.next()
        println(s"Affected rows: ${result3.rowCount()}")
      }
      case Failure(cause) => {
        println(s"$cause")
      }
    }
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

Note: Prepared statements binding OUT parameters is not supported for now.

== MySQL LOCAL INFILE

This client supports for handling the LOCAL INFILE Request, if you want to load data from a local file into the server, you can use query
`LOAD DATA LOCAL INFILE '<filename>' INTO TABLE <table>;`. More information can be found in the https://dev.mysql.com/doc/refman/8.0/en/load-data.html[MySQL Reference Manual].

== Authentication

MySQL 8.0 introduces a new authentication method named `caching_sha2_password` and it's the default one to authenticate.
In order to connect to the server using this new authentication method, you need either use a secure connection(i.e. enable TLS/SSL) or exchange the encrypted password using an RSA key pair to avoid leaks of password. The RSA key pair is automatically exchanged during the communication, but the server RSA public key may be hacked during the process since it's transferred on a insecure connection.
So if you're on a insecure connection and want to avoid the risk of exposing the server RSA public key, you can set the server RSA public key like this:

[source,scala]
----

var options1 = MySQLConnectOptions()
  .setPort(3306)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret")
  .setServerRsaPublicKeyPath("tls/files/public_key.pem")


var options2 = MySQLConnectOptions()
  .setPort(3306)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret")
  .setServerRsaPublicKeyValue(Buffer.buffer("-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3yvG5s0qrV7jxVlp0sMj\nxP0a6BuLKCMjb0o88hDsJ3xz7PpHNKazuEAfPxiRFVAV3edqfSiXoQw+lJf4haEG\nHQe12Nfhs+UhcAeTKXRlZP/JNmI+BGoBduQ1rCId9bKYbXn4pvyS/a1ft7SwFkhx\naogCur7iIB0WUWvwkQ0fEj/Mlhw93lLVyx7hcGFq4FOAKFYr3A0xrHP1IdgnD8QZ\n0fUbgGLWWLOossKrbUP5HWko1ghLPIbfmU6o890oj1ZWQewj1Rs9Er92/UDj/JXx\n7ha1P+ZOgPBlV037KDQMS6cUh9vTablEHsMLhDZanymXzzjBkL+wH/b9cdL16LkQ\n5QIDAQAB\n-----END PUBLIC KEY-----\n"))


----

More information about the `caching_sha2_password` authentication method can be found in the https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html[MySQL Reference Manual].

== Using SSL/TLS

To configure the client to use SSL connection, you can configure the `link:../dataobjects.html#MySQLConnectOptions[MySQLConnectOptions]`
like a Vert.x `NetClient`.
All https://dev.mysql.com/doc/refman/8.0/en/connection-options.html#option_general_ssl-mode[SSL modes] are supported and you are able to configure `sslmode`. The client is in `DISABLED` SSL mode by default.
`ssl` parameter is kept as a mere shortcut for setting `sslmode`. `setSsl(true)` is equivalent to `setSslMode(VERIFY_CA)` and `setSsl(false)` is equivalent to `setSslMode(DISABLED)`.

[source,scala]
----

var options = MySQLConnectOptions()
  .setPort(3306)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret")
  .setSslMode(SslMode.VERIFY_CA)
  .setPemTrustOptions(PemTrustOptions()
    .setCertPaths(Set("/path/to/cert.pem"))
  )


MySQLConnection.connect(vertx, options, {
  case Success(result) => {
    // Connected with SSL
  }
  case Failure(cause) => {
    println(s"$cause")
  }
})

----

More information can be found in the http://vertx.io/docs/vertx-core/java/#ssl[Vert.x documentation].

== MySQL utility command

Sometimes you want to use MySQL utility commands and we provide support for this.
More information can be found in the https://dev.mysql.com/doc/dev/mysql-server/8.0.12/page_protocol_command_phase_utility.html[MySQL utility commands].

=== COM_PING

You can use `COM_PING` command to check if the server is alive. The handler will be notified if the server responds to the PING, otherwise the handler will never be called.

[source,scala]
----
connection.pingFuture().onComplete{
  case Success(result) => println("Success")
  case Failure(cause) => println("Failure")
}

----

=== COM_RESET_CONNECTION

You can reset the session state with `COM_RESET_CONNECTION` command, this will reset the connection state like:
- user variables
- temporary tables
- prepared statements

[source,scala]
----
connection.resetConnectionFuture().onComplete{
  case Success(result) => {
    println("Connection has been reset now")
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

=== COM_CHANGE_USER

You can change the user of the current connection, this will perform a re-authentication and reset the connection state like `COM_RESET_CONNECTION`.

[source,scala]
----
var authenticationOptions = MySQLAuthOptions()
  .setUser("newuser")
  .setPassword("newpassword")
  .setDatabase("newdatabase")

connection.changeUserFuture(authenticationOptions).onComplete{
  case Success(result) => {
    println("User of current connection has been changed.")
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

=== COM_INIT_DB

You can use `COM_INIT_DB` command to change the default schema of the connection.

[source,scala]
----
connection.specifySchemaFuture("newschema").onComplete{
  case Success(result) => {
    println("Default schema changed to newschema")
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

=== COM_STATISTICS

You can use `COM_STATISTICS` command to get a human readable string of some internal status variables in MySQL server.

[source,scala]
----
connection.getInternalStatisticsFuture().onComplete{
  case Success(result) => {
    println(s"Statistics: ${result}")
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

=== COM_DEBUG

You can use `COM_DEBUG` command to dump debug info to the MySQL server's STDOUT.

[source,scala]
----
connection.debugFuture().onComplete{
  case Success(result) => {
    println("Debug info dumped to server's STDOUT")
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

=== COM_SET_OPTION

You can use `COM_SET_OPTION` command to set options for the current connection. Currently only `CLIENT_MULTI_STATEMENTS` can be set.

For example, you can disable `CLIENT_MULTI_STATEMENTS` with this command.

[source,scala]
----
connection.setOptionFuture(MySQLSetOption.MYSQL_OPTION_MULTI_STATEMENTS_OFF).onComplete{
  case Success(result) => {
    println("CLIENT_MULTI_STATEMENTS is off now")
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

== MySQL and MariaDB version support matrix

[cols="^,^,^,^", options="header"]
|====

2+| MySQL
2+| MariaDB

| Version | Supported | Version | Supported

|`5.5`
|&#10004;
|`10.1`
|&#10004;

|`5.6`
|&#10004;
|`10.2`
|&#10004;

|`5.7`
|&#10004;
|`10.3`
|&#10004;

|`8.0`
|&#10004;
|`10.4`
|&#10004;

|====

Known issues:

- Reset connection utility command does not work in MySQL 5.5, 5.6 and MariaDB 10.1
- Change user utility command is not supported with MariaDB 10.2 and 10.3