= Reactive PostgreSQL Client
:PREPARED_PARAMS: `$1`, `$2`, etc…​

The Reactive PostgreSQL Client is a client for PostgreSQL with a straightforward API focusing on
scalability and low overhead.

The client is reactive and non blocking, allowing to handle many database connections with a single thread.

* Event driven
* Lightweight
* Built-in connection pooling
* Prepared queries caching
* Publish / subscribe using PostgreSQL `NOTIFY/LISTEN`
* Batch and cursor
* Row streaming
* Command pipeling
* RxJava 1 and RxJava 2
* Direct memory to object without unnecessary copies
* Java 8 Date and Time
* SSL/TLS
* Unix domain socket
* HTTP/1.x CONNECT, SOCKS4a or SOCKS5 proxy support

== Usage

To use the Reactive PostgreSQL Client add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml]
----
<dependency>
 <groupId>${maven.groupId}</groupId>
 <artifactId>${maven.artifactId}</artifactId>
 <version>${maven.version}</version>
</dependency>
----
* Gradle (in your `build.gradle` file):

[source,groovy]
----
dependencies {
 compile '${maven.groupId}:${maven.artifactId}:${maven.version}'
}
----

== Getting started

Here is the simplest way to connect, query and disconnect

[source,scala]
----

// Connect options
var connectOptions = PgConnectOptions()
  .setPort(5432)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret")


// Pool options
var poolOptions = PoolOptions()
  .setMaxSize(5)


// Create the client pool
var client = PgPool.pool(connectOptions, poolOptions)

// A simple query
client.query("SELECT * FROM users WHERE id='julien'").executeFuture().onComplete{
  case Success(result) => println("Success")
  case Failure(cause) => println("Failure")
}

----

== Connecting to PostgreSQL

Most of the time you will use a pool to connect to PostgreSQL:

[source,scala]
----

// Connect options
var connectOptions = PgConnectOptions()
  .setPort(5432)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret")


// Pool options
var poolOptions = PoolOptions()
  .setMaxSize(5)


// Create the pooled client
var client = PgPool.pool(connectOptions, poolOptions)

----

The pooled client uses a connection pool and any operation will borrow a connection from the pool
to execute the operation and release it to the pool.

If you are running with Vert.x you can pass it your Vertx instance:

[source,scala]
----

// Connect options
var connectOptions = PgConnectOptions()
  .setPort(5432)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret")


// Pool options
var poolOptions = PoolOptions()
  .setMaxSize(5)

// Create the pooled client
var client = PgPool.pool(vertx, connectOptions, poolOptions)

----

You need to release the pool when you don't need it anymore:

[source,scala]
----

// Close the pool and all the associated resources
pool.close()

----

When you need to execute several operations on the same connection, you need to use a client
`link:../../scaladocs/io/vertx/scala/pgclient/PgConnection.html[connection]`.

You can easily get one from the pool:

[source,scala]
----

// Connect options
var connectOptions = PgConnectOptions()
  .setPort(5432)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret")


// Pool options
var poolOptions = PoolOptions()
  .setMaxSize(5)


// Create the pooled client
var client = PgPool.pool(vertx, connectOptions, poolOptions)

// Get a connection from the pool
client.getConnectionFuture().onComplete{
  case Success(result) => {

    println("Connected")

    // Obtain our connection
    var conn = result

    // All operations execute on the same connection
    conn.query("SELECT * FROM users WHERE id='julien'").executeFuture().onComplete{
      case Success(result) => {
        conn.query("SELECT * FROM users WHERE id='emad'").executeFuture().onComplete{
          case Success(result) => println("Success")
          case Failure(cause) => println("Failure")
        }
      }
      case Failure(cause) => {
        println(s"$cause")
      }
    }
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

Once you are done with the connection you must close it to release it to the pool, so it can be reused.

Sometimes you want to improve performance via Unix domain socket connection, we achieve this with Vert.x Native transports.

Make sure you have added the required `netty-transport-native` dependency in your classpath and enabled the Unix domain socket option.

[source,scala]
----

// Connect Options
// Socket file name will be /var/run/postgresql/.s.PGSQL.5432
var connectOptions = PgConnectOptions()
  .setHost("/var/run/postgresql")
  .setPort(5432)
  .setDatabase("the-db")


// Pool options
var poolOptions = PoolOptions()
  .setMaxSize(5)


// Create the pooled client
var client = PgPool.pool(connectOptions, poolOptions)

// Create the pooled client with a vertx instance
// Make sure the vertx instance has enabled native transports
var client2 = PgPool.pool(vertx, connectOptions, poolOptions)

----

More information can be found in the [Vert.x documentation](https://vertx.io/docs/vertx-core/java/#_native_transports).

== Configuration

There are several alternatives for you to configure the client.

=== data object

A simple way to configure the client is to specify a `PgConnectOptions` data object.

[source,scala]
----

// Data object
var connectOptions = PgConnectOptions()
  .setPort(5432)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret")


// Pool Options
var poolOptions = PoolOptions()
  .setMaxSize(5)


// Create the pool from the data object
var pool = PgPool.pool(vertx, connectOptions, poolOptions)

pool.getConnectionFuture().onComplete{
  case Success(result) => println("Success")
  case Failure(cause) => println("Failure")
}

----

You can also configure the generic properties with the `setProperties` or `addProperty` methods. Note `setProperties` will override the default client properties.

For example, you can set a default schema for the connection with adding a `search_path` property.

[source,scala]
----
Code not translatable
----

More information about the available properties can be found in the https://www.postgresql.org/docs/current/runtime-config-client.html[PostgreSQL Manuals].

=== connection uri

Apart from configuring with a `PgConnectOptions` data object, We also provide you an alternative way to connect when you want to configure with a connection URI:

[source,scala]
----

// Connection URI
var connectionUri = "postgresql://dbuser:secretpassword@database.server.com:3211/mydb"

// Create the pool from the connection URI
var pool = PgPool.pool(connectionUri)

// Create the connection from the connection URI
PgConnection.connect(vertx, connectionUri, {
  case Success(result) => println("Success")
  case Failure(cause) => println("Failure")
})

----

More information about connection string formats can be found in the https://www.postgresql.org/docs/9.6/static/libpq-connect.html#LIBPQ-CONNSTRING[PostgreSQL Manuals].

Currently the client supports the following parameter key words in connection uri

* host
* hostaddr
* port
* user
* password
* dbname
* sslmode
* properties including(application_name, fallback_application_name, search_path)

Note: configuring properties in connection URI will override the default properties.

=== environment variables

You can also use environment variables to set default connection setting values, this is useful
when you want to avoid hard-coding database connection information. You can refer to the https://www.postgresql.org/docs/9.6/static/libpq-envars.html[official documentation]
for more details. The following parameters are supported:

* `PGHOST`
* `PGHOSTADDR`
* `PGPORT`
* `PGDATABASE`
* `PGUSER`
* `PGPASSWORD`
* `PGSSLMODE`

If you don't specify a data object or a connection URI string to connect, environment variables will take precedence over them.

[source,scala]
----
$ PGUSER=user \
 PGHOST=the-host \
 PGPASSWORD=secret \
 PGDATABASE=the-db \
 PGPORT=5432 \
 PGSSLMODE=DISABLE
----

[source,scala]
----

// Create the pool from the environment variables
var pool = PgPool.pool()

// Create the connection from the environment variables
PgConnection.connect(vertx, {
  case Success(result) => println("Success")
  case Failure(cause) => println("Failure")
})

----

=== SASL SCRAM-SHA-256 authentication mechanism.

To use the sasl SCRAM-SHA-256 authentication add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml]
----
<dependency>
 <groupId>com.ongres.scram</groupId>
 <artifactId>client</artifactId>
 <version>1.0.0-beta.2</version>
</dependency>
----
* Gradle (in your `build.gradle` file):

[source,groovy]
----
dependencies {
 compile 'com.ongres.scram:client:1.0.0-beta.2'
}
----

Note that SCRAM-SHA-256-PLUS (added in Postgresql 11) is not supported.


include::queries.adoc[]

You can fetch generated keys with a 'RETURNING' clause in your query:

[source,scala]
----
client.preparedQuery("INSERT INTO color (color_name) VALUES ($1), ($2), ($3) RETURNING color_id").executeFuture(Tuple.of("white", "red", "blue")).onComplete{
  case Success(result) => {
    var rows = result
    println(rows.rowCount())
    rows.foreach(row => {
      println(s"generated key: ${row.getInteger("color_id")}")
    })

  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

include::connections.adoc[]

include::transactions.adoc[]

include::cursor.adoc[]

Note: PostreSQL destroys cursors at the end of a transaction, so the cursor API shall be used
within a transaction, otherwise you will likely get the `34000` PostgreSQL error.

== PostgreSQL type mapping

Currently the client supports the following PostgreSQL types

* BOOLEAN (`java.lang.Boolean`)
* INT2 (`java.lang.Short`)
* INT4 (`java.lang.Integer`)
* INT8 (`java.lang.Long`)
* FLOAT4 (`java.lang.Float`)
* FLOAT8 (`java.lang.Double`)
* CHAR (`java.lang.String`)
* VARCHAR (`java.lang.String`)
* TEXT (`java.lang.String`)
* ENUM (`java.lang.String`)
* NAME (`java.lang.String`)
* SERIAL2 (`java.lang.Short`)
* SERIAL4 (`java.lang.Integer`)
* SERIAL8 (`java.lang.Long`)
* NUMERIC (`io.vertx.sqlclient.data.Numeric`)
* UUID (`java.util.UUID`)
* DATE (`java.time.LocalDate`)
* TIME (`java.time.LocalTime`)
* TIMETZ (`java.time.OffsetTime`)
* TIMESTAMP (`java.time.LocalDateTime`)
* TIMESTAMPTZ (`java.time.OffsetDateTime`)
* INTERVAL (`io.vertx.pgclient.data.Interval`)
* BYTEA (`io.vertx.core.buffer.Buffer`)
* JSON (`io.vertx.core.json.JsonObject`, `io.vertx.core.json.JsonArray`, `Number`, `Boolean`, `String`, `io.vertx.sqlclient.Tuple#JSON_NULL`)
* JSONB (`io.vertx.core.json.JsonObject`, `io.vertx.core.json.JsonArray`, `Number`, `Boolean`, `String`, `io.vertx.sqlclient.Tuple#JSON_NULL`)
* POINT (`io.vertx.pgclient.data.Point`)
* LINE (`io.vertx.pgclient.data.Line`)
* LSEG (`io.vertx.pgclient.data.LineSegment`)
* BOX (`io.vertx.pgclient.data.Box`)
* PATH (`io.vertx.pgclient.data.Path`)
* POLYGON (`io.vertx.pgclient.data.Polygon`)
* CIRCLE (`io.vertx.pgclient.data.Circle`)
* TSVECTOR (`java.lang.String`)
* TSQUERY (`java.lang.String`)

Tuple decoding uses the above types when storing values, it also performs on the flu conversion the actual value when possible:

[source,scala]
----
pool.query("SELECT 1::BIGINT \"VAL\"").executeFuture().onComplete{
  case Success(result) => println("Success")
  case Failure(cause) => println("Failure")
}

----

Tuple encoding uses the above type mapping for encoding, unless the type is numeric in which case `java.lang.Number` is used instead:

[source,scala]
----
pool.query("SELECT 1::BIGINT \"VAL\"").executeFuture().onComplete{
  case Success(result) => println("Success")
  case Failure(cause) => println("Failure")
}

----

Arrays of these types are supported.

=== Handling JSON

PostgreSQL `JSON` and `JSONB` types are represented by the following Java types:

- `String`
- `Number`
- `Boolean`
- `io.vertx.core.json.JsonObject`
- `io.vertx.core.json.JsonArray`
- `io.vertx.sqlclient.Tuple#JSON_NULL` for representing the JSON null literal

[source,scala]
----
Code not translatable
----

=== Handling NUMERIC

The `Numeric` Java type is used to represent the PostgreSQL `NUMERIC` type.

[source,scala]
----
var numeric = row.get(io.vertx.sqlclient.data.Numeric.class, 0)
if (numeric.isNaN()) {
  // Handle NaN
} else {
  var value = numeric.bigDecimalValue()
}

----

== Handling arrays

Arrays are available on `link:../../scaladocs/io/vertx/scala/sqlclient/Tuple.html[Tuple]` and `link:../../scaladocs/io/vertx/scala/sqlclient/Row.html[Row]`:

[source,scala]
----
Code not translatable
----

== Handling custom types

Strings are used to represent custom types, both sent to and returned from Postgres.

You can read from PostgreSQL and get the custom type as a string

[source,scala]
----
client.preparedQuery("SELECT address, (address).city FROM address_book WHERE id=$1").executeFuture(Tuple.of(3)).onComplete{
  case Success(result) => {
    var rows = result
    rows.foreach(row => {
      println(s"Full Address ${row.getString(0)}, City ${row.getString(1)}")
    })

  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

You can also write to PostgreSQL by providing a string

[source,scala]
----
client.preparedQuery("INSERT INTO address_book (id, address) VALUES ($1, $2)").executeFuture(Tuple.of(3, "('Anytown', 'Second Ave', false)")).onComplete{
  case Success(result) => {
    var rows = result
    println(rows.rowCount())
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

== Handling text search

Text search is handling using java `String`

[source,scala]
----
client.preparedQuery("SELECT to_tsvector( $1 ) @@ to_tsquery( $2 )").executeFuture(Tuple.of("fat cats ate fat rats", "fat & rat")).onComplete{
  case Success(result) => {
    var rows = result
    rows.foreach(row => {
      println(s"Match : ${row.getBoolean(0)}")
    })

  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

`tsvector` and `tsquery` can be fetched from db using java `String`

[source,scala]
----
client.preparedQuery("SELECT to_tsvector( $1 ), to_tsquery( $2 )").executeFuture(Tuple.of("fat cats ate fat rats", "fat & rat")).onComplete{
  case Success(result) => {
    var rows = result
    rows.foreach(row => {
      println(s"Vector : ${row.getString(0)}, query : ${row.getString(1)}")
    })

  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

== Collector queries

You can use Java collectors with the query API:

[source,scala]
----
Code not translatable
----

The collector processing must not keep a reference on the `link:../../scaladocs/io/vertx/scala/sqlclient/Row.html[Row]` as
there is a single row used for processing the entire set.

The Java `Collectors` provides many interesting predefined collectors, for example you can
create easily create a string directly from the row set:

[source,scala]
----
Code not translatable
----

== Pub/sub

PostgreSQL supports pub/sub communication channels.

You can set a `link:../../scaladocs/io/vertx/scala/pgclient/PgConnection.html#notificationHandler()[notificationHandler]` to receive
PostgreSQL notifications:

[source,scala]
----

connection.notificationHandler((notification: io.vertx.scala.pgclient.PgNotification) => {
  println(s"Received ${todo-renderDataObjectMemberSelect} on channel ${todo-renderDataObjectMemberSelect}")
})

connection.query("LISTEN some-channel").executeFuture().onComplete{
  case Success(result) => println("Success")
  case Failure(cause) => println("Failure")
}

----

The `link:../../scaladocs/io/vertx/scala/pgclient/pubsub/PgSubscriber.html[PgSubscriber]` is a channel manager managing a single connection that
provides per channel subscription:

[source,scala]
----

var subscriber = PgSubscriber.subscriber(vertx, PgConnectOptions()
  .setPort(5432)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret")
)

// You can set the channel before connect
subscriber.channel("channel1").handler((payload: java.lang.String) => {
  println(s"Received ${payload}")
})

subscriber.connectFuture().onComplete{
  case Success(result) => {

    // Or you can set the channel after connect
    subscriber.channel("channel2").handler((payload: java.lang.String) => {
      println(s"Received ${payload}")
    })
  }
  case Failure(cause) => println("Failure")
}

----

The channel name that is given to the channel method will be the exact name of the channel as held by PostgreSQL for sending
notifications.  Note this is different than the representation of the channel name in SQL, and
internally `link:../../scaladocs/io/vertx/scala/pgclient/pubsub/PgSubscriber.html[PgSubscriber]` will prepare the submitted channel name as a quoted identifier:

[source,scala]
----

var subscriber = PgSubscriber.subscriber(vertx, PgConnectOptions()
  .setPort(5432)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret")
)

subscriber.connectFuture().onComplete{
  case Success(result) => {
    // Complex channel name - name in PostgreSQL requires a quoted ID
    subscriber.channel("Complex.Channel.Name").handler((payload: java.lang.String) => {
      println(s"Received ${payload}")
    })
    subscriber.channel("Complex.Channel.Name").subscribeHandler((subscribed: java.lang.Void) => {
      subscriber.actualConnection().query("NOTIFY \"Complex.Channel.Name\", 'msg'").executeFuture().onComplete{
        case Success(result) => println("Success")
        case Failure(cause) => println("Failure")
      }
    })

    // PostgreSQL simple ID's are forced lower-case
    subscriber.channel("simple_channel").handler((payload: java.lang.String) => {
      println(s"Received ${payload}")
    })
    subscriber.channel("simple_channel").subscribeHandler((subscribed: java.lang.Void) => {
      // The following simple channel identifier is forced to lower case
      subscriber.actualConnection().query("NOTIFY Simple_CHANNEL, 'msg'").executeFuture().onComplete{
        case Success(result) => println("Success")
        case Failure(cause) => println("Failure")
      }
    })

    // The following channel name is longer than the current
    // (NAMEDATALEN = 64) - 1 == 63 character limit and will be truncated
    subscriber.channel("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbb").handler((payload: java.lang.String) => {
      println(s"Received ${payload}")
    })
  }
  case Failure(cause) => println("Failure")
}

----
You can provide a reconnect policy as a function that takes the number of `retries` as argument and returns an `amountOfTime`
value:

* when `amountOfTime < 0`: the subscriber is closed and there is no retry
* when `amountOfTime = 0`: the subscriber retries to connect immediately
* when `amountOfTime > 0`: the subscriber retries after `amountOfTime` milliseconds

[source,scala]
----

var subscriber = PgSubscriber.subscriber(vertx, PgConnectOptions()
  .setPort(5432)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret")
)

// Reconnect at most 10 times after 100 ms each
subscriber.reconnectPolicy((retries: java.lang.Integer) => {
  if (retries < 10) {
    100
  } else {
    -1
  }
})

----

The default policy is to not reconnect.

== Cancelling Request

PostgreSQL supports cancellation of requests in progress. You can cancel inflight requests using `link:../../scaladocs/io/vertx/scala/pgclient/PgConnection.html#cancelRequest()[cancelRequest]`. Cancelling a request opens a new connection to the server and cancels the request and then close the connection.

[source,scala]
----
connection.query("SELECT pg_sleep(20)").executeFuture().onComplete{
  case Success(result) => {
    // imagine this is a long query and is still running
    println("Query success")
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}
connection.cancelRequestFuture().onComplete{
  case Success(result) => {
    println("Cancelling request has been sent")
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

> The cancellation signal might or might not have any effect — for example, if it arrives after the backend has finished processing the query, then it will have no effect. If the cancellation is effective, it results in the current command being terminated early with an error message.

More information can be found in the https://www.postgresql.org/docs/11/protocol-flow.html#id-1.10.5.7.9[official documentation].

== Using SSL/TLS

To configure the client to use SSL connection, you can configure the `link:../dataobjects.html#PgConnectOptions[PgConnectOptions]`
like a Vert.x `NetClient`.
All https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-PROTECTION[SSL modes] are supported and you are able to configure `sslmode`. The client is in `DISABLE` SSL mode by default.
`ssl` parameter is kept as a mere shortcut for setting `sslmode`. `setSsl(true)` is equivalent to `setSslMode(VERIFY_CA)` and `setSsl(false)` is equivalent to `setSslMode(DISABLE)`.

[source,scala]
----

var options = PgConnectOptions()
  .setPort(5432)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret")
  .setSslMode(SslMode.VERIFY_CA)
  .setPemTrustOptions(PemTrustOptions()
    .setCertPaths(Set("/path/to/cert.pem"))
  )


PgConnection.connect(vertx, options, {
  case Success(result) => {
    // Connected with SSL
  }
  case Failure(cause) => {
    println(s"$cause")
  }
})

----

More information can be found in the http://vertx.io/docs/vertx-core/java/#ssl[Vert.x documentation].

== Using a proxy

You can also configure the client to use an HTTP/1.x CONNECT, SOCKS4a or SOCKS5 proxy.

More information can be found in the http://vertx.io/docs/vertx-core/java/#_using_a_proxy_for_client_connections[Vert.x documentation].

ifeval::["scala" == "java"]
include::override/rxjava2.adoc[]
endif::[]