= Cheatsheets

[[Config]]
== Config

++++
 A configuration object containing the configuration entries for a resource
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|===

[[ConfigEntry]]
== ConfigEntry

++++
 A class representing a configuration entry containing name, value and additional metadata
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[default]]`@default`|`Boolean`|+++
Set whether the config value is the default or if it's been explicitly set
+++
|[[name]]`@name`|`String`|+++
Set the config name
+++
|[[readOnly]]`@readOnly`|`Boolean`|+++
Set whether the config is read-only and cannot be updated
+++
|[[sensitive]]`@sensitive`|`Boolean`|+++
Set whether the config value is sensitive. The value is always set to null by the broker if the config value is sensitive
+++
|[[source]]`@source`|`link:enums.html#ConfigSource[ConfigSource]`|+++
Set the source of this configuration entry
+++
|[[value]]`@value`|`String`|+++
Set the value or null. Null is returned if the config is unset or if isSensitive is true
+++
|===

[[ConfigResource]]
== ConfigResource

++++
 A class representing resources that have configuration
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[default]]`@default`|`Boolean`|+++
Set if this is the default resource of a resource type. Resource name is empty for the default resource.
+++
|[[name]]`@name`|`String`|+++
Set the resource name
+++
|[[type]]`@type`|`link:enums.html#Type[Type]`|+++
Set the resource type
+++
|===

[[ConfigSynonym]]
== ConfigSynonym

++++
 Class representing a configuration synonym of a link
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[name]]`@name`|`String`|+++
Set the name of this configuration
+++
|[[source]]`@source`|`link:enums.html#ConfigSource[ConfigSource]`|+++
Set the source of this configuration
+++
|[[value]]`@value`|`String`|+++
Set the value of this configuration, which may be null if the configuration is sensitive
+++
|===

[[ConsumerGroupDescription]]
== ConsumerGroupDescription

++++
 A detailed description of a single consumer group in the cluster
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[groupId]]`@groupId`|`String`|+++
Set the id of the consumer group
+++
|[[partitionAssignor]]`@partitionAssignor`|`String`|+++
Set the consumer group partition assignor
+++
|[[simpleConsumerGroup]]`@simpleConsumerGroup`|`Boolean`|+++
Set if consumer group is simple or not
+++
|[[state]]`@state`|`link:enums.html#ConsumerGroupState[ConsumerGroupState]`|+++
Set the consumer group state, or UNKNOWN if the state is too new for us to parse
+++
|===

[[ConsumerGroupListing]]
== ConsumerGroupListing

++++
 A listing of a consumer group in the cluster.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[groupId]]`@groupId`|`String`|+++
Set the consumer group id
+++
|[[simpleConsumerGroup]]`@simpleConsumerGroup`|`Boolean`|+++
Set if consumer group is simple or not
+++
|===

[[MemberAssignment]]
== MemberAssignment

++++
 A description of the assignments of a specific group member
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|===

[[MemberDescription]]
== MemberDescription

++++
 A detailed description of a single group instance in the cluster
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[clientId]]`@clientId`|`String`|+++
Set the client id of the group member
+++
|[[consumerId]]`@consumerId`|`String`|+++
Set the consumer id of the group member
+++
|[[host]]`@host`|`String`|+++
Set the host where the group member is running
+++
|===

[[NewTopic]]
== NewTopic

++++
 A new topic to be created
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`String`|+++
Set the configuration for the new topic or null if no configs ever specified
+++
|[[name]]`@name`|`String`|+++
Set the name of the topic to be created
+++
|[[numPartitions]]`@numPartitions`|`Number (int)`|+++
Set the number of partitions for the new topic or -1 if a replica assignment has been specified
+++
|[[replicationFactor]]`@replicationFactor`|`Number (short)`|+++
Set the replication factor for the new topic or -1 if a replica assignment has been specified
+++
|===

[[Node]]
== Node

++++
 Information about a Kafka cluster node
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[empty]]`@empty`|`Boolean`|+++

+++
|[[hasRack]]`@hasRack`|`Boolean`|+++
Set if this node has a defined rack
+++
|[[host]]`@host`|`String`|+++
Set the host name for this node
+++
|[[id]]`@id`|`Number (int)`|+++
Set the node id of this node
+++
|[[idString]]`@idString`|`String`|+++
Set the string representation of the node id
+++
|[[isEmpty]]`@isEmpty`|`Boolean`|+++
Set if this node is empty
+++
|[[port]]`@port`|`Number (int)`|+++
Set the port for this node
+++
|[[rack]]`@rack`|`String`|+++
Set the rack for this node
+++
|===

[[OffsetAndMetadata]]
== OffsetAndMetadata

++++
 Provide additional metadata when an offset is committed
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[metadata]]`@metadata`|`String`|+++
Set additional metadata for the offset committed
+++
|[[offset]]`@offset`|`Number (long)`|+++
Set the offset to commit
+++
|===

[[OffsetAndTimestamp]]
== OffsetAndTimestamp

++++
 Represent information related to a Offset with timestamp information
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[offset]]`@offset`|`Number (long)`|+++
Set the offset
+++
|[[timestamp]]`@timestamp`|`Number (long)`|+++
Set the timestamp
+++
|===

[[PartitionInfo]]
== PartitionInfo

++++
 Information about a specific Kafka topic partition
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[partition]]`@partition`|`Number (int)`|+++
Set the partition id
+++
|[[topic]]`@topic`|`String`|+++
Set the topic name
+++
|===

[[RecordMetadata]]
== RecordMetadata

++++
 Metadata related to a Kafka record
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[checksum]]`@checksum`|`Number (long)`|+++
Set the checksum (CRC32) of the record.
+++
|[[offset]]`@offset`|`Number (long)`|+++
Set the offset of the record in the topic/partition.
+++
|[[partition]]`@partition`|`Number (int)`|+++
Set the partition the record was sent to
+++
|[[timestamp]]`@timestamp`|`Number (long)`|+++
Set the timestamp of the record in the topic/partition
+++
|[[topic]]`@topic`|`String`|+++
Set the topic the record was appended to
+++
|===

[[TopicDescription]]
== TopicDescription

++++
 A detailed description of a single topic in the cluster
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[internal]]`@internal`|`Boolean`|+++
Set whether the topic is internal to Kafka.
+++
|[[name]]`@name`|`String`|+++
Set the name of the topic.
+++
|===

[[TopicPartition]]
== TopicPartition

++++
 Represent information related to a partition for a topic
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[partition]]`@partition`|`Number (int)`|+++
Set the partition number
+++
|[[topic]]`@topic`|`String`|+++
Set the topic name
+++
|===

[[TopicPartitionInfo]]
== TopicPartitionInfo

++++
 A class containing leadership, replicas and ISR information for a topic partition.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[partition]]`@partition`|`Number (int)`|+++
Set the partition id
+++
|===

