== Using transactions

=== Transactions with connections

You can execute transaction using SQL `BEGIN`/`COMMIT`/`ROLLBACK`, if you do so you must use
a `link:../../scaladocs/io/vertx/scala/sqlclient/SqlConnection.html[SqlConnection]` and manage it yourself.

Or you can use the transaction API of `link:../../scaladocs/io/vertx/scala/sqlclient/SqlConnection.html[SqlConnection]`:

[source,scala]
----
`transaction01`
----

When the database server reports the current transaction is failed (e.g the infamous _current transaction is aborted, commands ignored until
end of transaction block_), the transaction is rollbacked and the `link:../../scaladocs/io/vertx/scala/sqlclient/Transaction.html#abortHandler()[abortHandler]`
is called:

[source,scala]
----
`transaction02`
----

=== Simplified transaction API

When you use a pool, you can start a transaction directly on the pool.

It borrows a connection from the pool, begins the transaction and releases the connection to the pool when the transaction ends.

[source,scala]
----
`transaction03`
----

NOTE: this code will not close the connection because it will always be released back to the pool when the transaction