== Running queries

When you don't need a transaction or run single queries, you can run queries directly on the pool; the pool
will use one of its connection to run the query and return the result to you.

Here is how to run simple queries:

[source,scala]
----
client.query("SELECT * FROM users WHERE id='julien'").executeFuture().onComplete{
  case Success(result) => {
    var result = result
    println(s"Got ${result.size()} rows ")
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

=== Prepared queries

You can do the same with prepared queries.

The SQL string can refer to parameters by position, using the database syntax {PREPARED_PARAMS}

[source,scala]
----
client.preparedQuery("SELECT * FROM users WHERE id=$1").executeFuture(Tuple.of("julien")).onComplete{
  case Success(result) => {
    var rows = result
    println(s"Got ${rows.size()} rows ")
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

Query methods provides an asynchronous `link:../../scaladocs/io/vertx/scala/sqlclient/RowSet.html[RowSet]` instance that works for _SELECT_ queries

[source,scala]
----
client.preparedQuery("SELECT first_name, last_name FROM users").executeFuture().onComplete{
  case Success(result) => {
    var rows = result
    rows.foreach(row => {
      println(s"User ${row.getString(0)} ${row.getString(1)}")
    })

  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

or _UPDATE_/_INSERT_ queries:

[source,scala]
----
client.preparedQuery("INSERT INTO users (first_name, last_name) VALUES ($1, $2)").executeFuture(Tuple.of("Julien", "Viet")).onComplete{
  case Success(result) => {
    var rows = result
    println(rows.rowCount())
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

The `link:../../scaladocs/io/vertx/scala/sqlclient/Row.html[Row]` gives you access to your data by index

[source,scala]
----
println(s"User ${row.getString(0)} ${row.getString(1)}")

----

or by name

[source,scala]
----
println(s"User ${row.getString("first_name")} ${row.getString("last_name")}")

----

The client will not do any magic here and the column name is identified with the name in the table regardless of how your SQL text is.

You can access a wide variety of of types

[source,scala]
----

var firstName = row.getString("first_name")
var male = row.getBoolean("male")
var age = row.getInteger("age")

// ...


----

You can use cached prepared statements to execute one-shot prepared queries:

[source,scala]
----

// Enable prepare statements caching
connectOptions.setCachePreparedStatements(true)
client.preparedQuery("SELECT * FROM users WHERE id = $1").executeFuture(Tuple.of("julien")).onComplete{
  case Success(result) => {
    var rows = result
    println(s"Got ${rows.size()} rows ")
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

You can create a `PreparedStatement` and manage the lifecycle by yourself.

[source,scala]
----
sqlConnection.prepareFuture("SELECT * FROM users WHERE id = $1").onComplete{
  case Success(result) => {
    var preparedStatement = result
    preparedStatement.query().executeFuture(Tuple.of("julien")).onComplete{
      case Success(result) => {
        var rows = result
        println(s"Got ${rows.size()} rows ")
        preparedStatement.close()
      }
      case Failure(cause) => {
        println(s"$cause")
      }
    }
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

=== Batches

You can execute prepared batch

[source,scala]
----

// Add commands to the batch
var batch = List()
batch :::= List(Tuple.of("julien", "Julien Viet"))
batch :::= List(Tuple.of("emad", "Emad Alblueshi"))

// Execute the prepared batch
client.preparedQuery("INSERT INTO USERS (id, name) VALUES ($1, $2)").executeBatchFuture(batch).onComplete{
  case Success(result) => {

    // Process rows
    var rows = result
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----