== Using the file system with Vert.x

The Vert.x `link:../../scaladoc/io/vertx/scala/core/file/FileSystem.html[FileSystem]` object provides many operations for manipulating the file system.

There is one file system object per Vert.x instance, and you obtain it with  `link:../../scaladoc/io/vertx/scala/core/Vertx.html#fileSystem()[fileSystem]`.

A blocking and a non blocking version of each operation is provided. The non blocking versions take a handler
which is called when the operation completes or an error occurs.

Here's an example of an asynchronous copy of a file:

[source,scala]
----
import scala.util.Failure
import scala.util.Success
var fs = vertx.fileSystem()

// Copy file from foo.txt to bar.txt
fs.copyFuture("foo.txt", "bar.txt").onComplete{
  case Success(result) => {
    // Copied ok!
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----
The blocking versions are named `xxxBlocking` and return the results or throw exceptions directly. In many
cases, depending on the operating system and file system, some of the potentially blocking operations can return
quickly, which is why we provide them, but it's highly recommended that you test how long they take to return in your
particular application before using them from an event loop, so as not to break the Golden Rule.

Here's the copy using the blocking API:

[source,scala]
----
var fs = vertx.fileSystem()

// Copy file from foo.txt to bar.txt synchronously
fs.copyBlocking("foo.txt", "bar.txt")

----

Many operations exist to copy, move, truncate, chmod and many other file operations. We won't list them all here,
please consult the `link:../../scaladoc/io/vertx/scala/core/file/FileSystem.html[API docs]` for the full list.

Let's see a couple of examples using asynchronous methods:

[source,scala]
----
import scala.util.Failure
import scala.util.Success
import io.vertx.scala.core.buffer.Buffer
import io.vertx.scala.core.Vertx
var vertx = Vertx.vertx()

// Read a file
vertx.fileSystem().readFileFuture("target/classes/readme.txt").onComplete{
  case Success(result) => {
    println(result)
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

// Copy a file
vertx.fileSystem().copyFuture("target/classes/readme.txt", "target/classes/readme2.txt").onComplete{
  case Success(result) => {
    println("File copied")
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

// Write a file
vertx.fileSystem().writeFileFuture("target/classes/hello.txt", Buffer.buffer("Hello")).onComplete{
  case Success(result) => {
    println("File written")
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

// Check existence and delete
vertx.fileSystem().existsFuture("target/classes/junk.txt").onComplete{
  case Success(result) => println("Success")
  case Failure(cause) => println("Failure")
}

----

=== Asynchronous files

Vert.x provides an asynchronous file abstraction that allows you to manipulate a file on the file system.

You open an `link:../../scaladoc/io/vertx/scala/core/file/AsyncFile.html[AsyncFile]` as follows:

[source,scala]
----
import scala.util.Failure
import scala.util.Success
var options = OpenOptions()
fileSystem.openFuture("myfile.txt", options).onComplete{
  case Success(result) => {
    var file = result
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

`AsyncFile` implements `ReadStream` and `WriteStream` so you can _pump_
files to and from other stream objects such as net sockets, http requests and responses, and WebSockets.

They also allow you to read and write directly to them.

==== Random access writes

To use an `AsyncFile` for random access writing you use the
`link:../../scaladoc/io/vertx/scala/core/file/AsyncFile.html#write(io.vertx.core.buffer.Buffer,%20long,%20io.vertx.core.Handler)[write]` method.

The parameters to the method are:

* `buffer`: the buffer to write.
* `position`: an integer position in the file where to write the buffer. If the position is greater or equal to the size
 of the file, the file will be enlarged to accommodate the offset.
* `handler`: the result handler

Here is an example of random access writes:

[source,scala]
----
import scala.util.Failure
import scala.util.Success
import io.vertx.scala.core.buffer.Buffer
import io.vertx.scala.core.Vertx
var vertx = Vertx.vertx()
vertx.fileSystem().openFuture("target/classes/hello.txt", OpenOptions()).onComplete{
  case Success(result) => {
    var file = result
    var buff = Buffer.buffer("foo")
    for ( i <- 0 until 5) {
      file.writeFuture(buff, buff.length() * i).onComplete{
        case Success(result) => {
          println("Written ok!")
          // etc
        }
        case Failure(cause) => {
          println(s"$cause")
        }
      }
    }

  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

==== Random access reads

To use an `AsyncFile` for random access reads you use the
`link:../../scaladoc/io/vertx/scala/core/file/AsyncFile.html#read(io.vertx.core.buffer.Buffer,%20int,%20long,%20int,%20io.vertx.core.Handler)[read]`
method.

The parameters to the method are:

* `buffer`: the buffer into which the data will be read.
* `offset`: an integer offset into the buffer where the read data will be placed.
* `position`: the position in the file where to read data from.
* `length`: the number of bytes of data to read
* `handler`: the result handler

Here's an example of random access reads:

[source,scala]
----
import scala.util.Failure
import scala.util.Success
import io.vertx.scala.core.buffer.Buffer
import io.vertx.scala.core.Vertx
var vertx = Vertx.vertx()
vertx.fileSystem().openFuture("target/classes/les_miserables.txt", OpenOptions()).onComplete{
  case Success(result) => {
    var file = result
    var buff = Buffer.buffer(1000)
    for ( i <- 0 until 10) {
      file.readFuture(buff, i * 100, i * 100, 100).onComplete{
        case Success(result) => {
          println("Read ok!")
        }
        case Failure(cause) => {
          println(s"$cause")
        }
      }
    }

  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

==== Opening Options

When opening an `AsyncFile`, you pass an `link:../dataobjects.html#OpenOptions[OpenOptions]` instance.
These options describe the behavior of the file access. For instance, you can configure the file permissions with the
`link:../dataobjects.html#OpenOptions#setRead(boolean)[read]`, `link:../dataobjects.html#OpenOptions#setWrite(boolean)[write]`
and `link:../dataobjects.html#OpenOptions#setPerms(java.lang.String)[perms]` methods.

You can also configure the behavior if the open file already exists with
`link:../dataobjects.html#OpenOptions#setCreateNew(boolean)[createNew]` and
`link:../dataobjects.html#OpenOptions#setTruncateExisting(boolean)[truncateExisting]`.

You can also mark the file to be deleted on
close or when the JVM is shutdown with `link:../dataobjects.html#OpenOptions#setDeleteOnClose(boolean)[deleteOnClose]`.

==== Flushing data to underlying storage.

In the `OpenOptions`, you can enable/disable the automatic synchronisation of the content on every write using
`link:../dataobjects.html#OpenOptions#setDsync(boolean)[dsync]`. In that case, you can manually flush any writes from the OS
cache by calling the `link:../../scaladoc/io/vertx/scala/core/file/AsyncFile.html#flush()[flush]` method.

This method can also be called with an handler which will be called when the flush is complete.

==== Using AsyncFile as ReadStream and WriteStream

`AsyncFile` implements `ReadStream` and `WriteStream`. You can then
use them with a _pump_ to pump data to and from other read and write streams. For example, this would
copy the content to another `AsyncFile`:

[source,scala]
----
import scala.util.Failure
import scala.util.Success
import io.vertx.scala.core.streams.Pump
import io.vertx.scala.core.Vertx
var vertx = Vertx.vertx()
var output = vertx.fileSystem().openBlocking("target/classes/plagiary.txt", OpenOptions())

vertx.fileSystem().openFuture("target/classes/les_miserables.txt", OpenOptions()).onComplete{
  case Success(result) => {
    var file = result
    Pump.pump(file, output).start()
    file.endHandler((r: java.lang.Void) => {
      println("Copy done")
    })
  }
  case Failure(cause) => {
    println(s"$cause")
  }
}

----

You can also use the _pump_ to write file content into HTTP responses, or more generally in any
`WriteStream`.

[[classpath]]
==== Accessing files from the classpath

When vert.x cannot find the file on the filesystem it tries to resolve the
file from the class path. Note that classpath resource paths never start with
a `/`. 

Due to the fact that Java does not offer async access to classpath
resources, the file is copied to the filesystem in a worker thread when the
classpath resource is accessed the very first time and served from there
asynchrously. When the same resource is accessed a second time, the file from
the filesystem is served directly from the filesystem. The original content
is served even if the classpath resource changes (e.g. in a development
system). 

This caching behaviour can be disabled by setting the system
property `vertx.disableFileCaching` to `true`. The path where the files are
cached is `.vertx` by default and can be customized by setting the system
property `vertx.cacheDirBase`.

The whole classpath resolving feature can be disabled by setting the system
property `vertx.disableFileCPResolving` to `true`.

NOTE: these system properties are evaluated once when the the `io.vertx.core.impl.FileResolver` class is loaded, so
these properties should be set before loading this class or as a JVM system property when launching it.

==== Closing an AsyncFile

To close an `AsyncFile` call the `link:../../scaladoc/io/vertx/scala/core/file/AsyncFile.html#close()[close]` method. Closing is asynchronous and
if you want to be notified when the close has been completed you can specify a handler function as an argument.