/*
 * Copyright 2014 Red Hat, Inc.
 *
 * Red Hat licenses this file to you under the Apache License, version 2.0
 * (the "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

package io.vertx.scala.ext.web.handler

import io.vertx.lang.scala.HandlerOps._
import scala.compat.java8.FunctionConverters._
import scala.collection.JavaConverters._
import io.vertx.ext.web.handler.{CSRFHandler => JCSRFHandler}
  import io.vertx.ext.web.{RoutingContext => JRoutingContext}
import io.vertx.scala.ext.web.RoutingContext
import io.vertx.ext.web.{RoutingContext => JRoutingContext}
      import io.vertx.ext.web.handler.{CSRFHandler => JCSRFHandler}

/**
  * This handler adds a CSRF token to requests which mutate state. In order change the state a (XSRF-TOKEN) cookie is set
  * with a unique token, that is expected to be sent back in a (X-XSRF-TOKEN) header.
  *
  * The behavior is to check the request body header and cookie for validity.
  *
  * This Handler requires session support, thus should be added somewhere below Session and Body handlers.
  */
class CSRFHandler(private val _asJava: JCSRFHandler) {

  def asJava: JCSRFHandler = _asJava

  def handle(arg0: RoutingContext): Unit = {
    _asJava.handle(arg0.asJava.asInstanceOf[JRoutingContext])
  }

  /**
    * Set the cookie name. By default XSRF-TOKEN is used as it is the expected name by AngularJS however other frameworks
    * might use other names.
    * @param name a new name for the cookie.
    * @return fluent
    */
  def setCookieName(name: String): CSRFHandler = {
    _asJava.setCookieName(name)
    this
  }

  /**
    * Set the header name. By default X-XSRF-TOKEN is used as it is the expected name by AngularJS however other
    * frameworks might use other names.
    * @param name a new name for the header.
    * @return fluent
    */
  def setHeaderName(name: String): CSRFHandler = {
    _asJava.setHeaderName(name)
    this
  }

  /**
    * Should the handler give warning messages if this handler is used in other than https protocols?
    * @param nag true to nag
    * @return fluent
    */
  def setNagHttps(nag: Boolean): CSRFHandler = {
    _asJava.setNagHttps(nag)
    this
  }

  /**
    * Set the timeout for tokens generated by the handler, by default it uses the default from the session handler.
    * @param timeout token timeout
    * @return fluent
    */
  def setTimeout(timeout: Long): CSRFHandler = {
    _asJava.setTimeout(timeout)
    this
  }

}

object CSRFHandler {

  def apply(_asJava: JCSRFHandler): CSRFHandler =
    new CSRFHandler(_asJava)

  def create(secret: String): CSRFHandler = {
    CSRFHandler.apply(io.vertx.ext.web.handler.CSRFHandler.create(secret))
  }

}
