= Cheatsheets

[[ReportOptions]]
== ReportOptions

++++
 Configures a reporter consisting in a name <code>to</code>, an address <code>at</code> and an optional <code>format</code>.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[format]]`format`|`String`|
+++
Set the current reporter format.
+++
|[[to]]`to`|`String`|
+++
Set the current reporter name.
+++
|===

[[ReportingOptions]]
== ReportingOptions

++++
 Reporting options:

 <ul>
   <li>the <code>reporters</code> is an array of reporter configurations</li>
 </ul>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[reporters]]`reporters`|`Array of link:dataobjects.html#ReportOptions[ReportOptions]`|
+++
Replace the current list of reporters with a new one.
+++
|===

[[TestOptions]]
== TestOptions

++++
 Test execution options:

 <ul>
   <li>the <code>timeout</code> in milliseconds, the default value is 2 minutes </li>
   <li>the <code>useEventLoop</code></li> configures the event loop usage
     <ul>
       <li><code>true</code> always runs with an event loop</li>
       <li><code>false</code> never runs with an event loop</li>
       <li><code>null</code> uses an event loop if there is one (provided by link)
       otherwise run without</li>
     </ul>
   </li>
   <li>the <code>reporters</code> is an array of reporter configurations</li>
 </ul>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[reporters]]`reporters`|`Array of link:dataobjects.html#ReportOptions[ReportOptions]`|
+++
Replace the current list of reporters with a new one.
+++
|[[timeout]]`timeout`|`Number (long)`|
+++
Set the test timeout.
+++
|[[useEventLoop]]`useEventLoop`|`Boolean`|
+++
Configure the execution to use an event loop when there is no one existing.
+++
|===

