== Running queries

When you don't need a transaction or run single queries, you can run queries directly on the pool; the pool
will use one of its connection to run the query and return the result to you.

Here is how to run simple queries:

[source,scala]
----
`queries01`
----

=== Prepared queries

You can do the same with prepared queries.

The SQL string can refer to parameters by position, using the database syntax {PREPARED_PARAMS}

[source,scala]
----
`queries02`
----

Query methods provides an asynchronous `link:../../scaladocs/io/vertx/scala/sqlclient/RowSet.html[RowSet]` instance that works for _SELECT_ queries

[source,scala]
----
`queries03`
----

or _UPDATE_/_INSERT_ queries:

[source,scala]
----
`queries04`
----

The `link:../../scaladocs/io/vertx/scala/sqlclient/Row.html[Row]` gives you access to your data by index

[source,scala]
----
`queries05`
----

or by name

[source,scala]
----
`queries06`
----

The client will not do any magic here and the column name is identified with the name in the table regardless of how your SQL text is.

You can access a wide variety of of types

[source,scala]
----
`queries07`
----

You can use cached prepared statements to execute one-shot prepared queries:

[source,scala]
----
`queries09`
----

You can create a `PreparedStatement` and manage the lifecycle by yourself.

[source,scala]
----
`queries10`
----

=== Batches

You can execute prepared batch

[source,scala]
----
`queries08`
----